Save next nodes in Floyd-Warshall numpy variants for path reconstruction
Qiskit/rustworkx pull request #1040
Opened 2023-12-17 09:44 UTC by kazuki0824

2023-12-17 09:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/rustworkx?pullRequest=1040) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/rustworkx?pullRequest=1040) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/rustworkx?pullRequest=1040) it.</sub>

2023-12-17 23:20 UTC, IvanIsCoding reviewed
Thanks for making your first contribution! I agree that we can add predecessors to `floydwarshall_numpy`.

However, changing the return type is a breaking change. It will also fail all our tests, which should give you a hint that it is not exactly the change you're looking to make.

Can you create a new function `rustworkx.floyd_warshall_predecessor_and_distance` to incorporate the new code? It would be akin to  https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.dense.floyd_warshall_predecessor_and_distance.html

2023-12-17 23:20 UTC, IvanIsCoding commented on src/shortest_path/floyd_warshall.rs
> +) -> PyResult<(Array2<f64>, Array2<usize>)> {
Can you separate this code into a new function?

2023-12-20 15:57 UTC, kazuki0824 commented
@IvanIsCoding now that the new implementations are separated to not break existing APIs

2023-12-22 09:01 UTC, kazuki0824 commented
If we choose predecessors to represent shortest paths, it may cause much more change of the parallelism implementation than the case we choose successor.

2023-12-22 19:09 UTC, IvanIsCoding commented
> If we choose predecessors to represent shortest paths, it may cause much more change of the parallelism implementation than the case we choose successors. That's why I don't use predecessors.

I won’t have time to review this week but I hope to get a review by January 2. In the meantime, I encourage you to write unit tests. You can simply copy the existing Floyd Warshall test cases and reuse them for the new methods

2024-01-01 17:18 UTC, IvanIsCoding requested changes
Overall the code looks correct, thanks for implementing it!

There are two items we need to address however:
* It would be best to split the code path for the predecessors from the code path for Floyd Warshall Numpy. The additional overhead of the extra memory doubles the memory consumption in a function that already uses O(n^2) memory. So I'd rather keep the constant down
* We need to add tests for correctness. See https://github.com/Qiskit/rustworkx/blob/main/tests/rustworkx_tests/graph/test_floyd_warshall.py and https://github.com/Qiskit/rustworkx/blob/main/tests/rustworkx_tests/digraph/test_floyd_warshall.py for examples

2024-01-01 17:18 UTC, IvanIsCoding commented on src/shortest_path/floyd_warshall.rs
> +) -> PyResult<(Array2<f64>, Array2<usize>)> {
Can you duplicate this code? I think the overall implementation is fine but I don't want to add the extra overhead of keeping the predecessors for the existing `floyd_warshall_numpy`

2024-01-05 07:50 UTC, kazuki0824 commented
> It would be best to split the code path for the predecessors from the code path for Floyd Warshall Numpy. The additional overhead of the extra memory doubles the memory consumption in a function that already uses O(n^2) memory. So I'd rather keep the constant down

I got it and resolved by an extra argument `generate_successors`. The new `floyd_warshall_numpy` returns a pair, whose latter part is Option<Array2<usize>>, and it has content only if  `generate_successors` is true.

2024-01-06 04:34 UTC, IvanIsCoding approved these changes
LGTM, thanks for making your first contribution!

I am going to merge this soon, but as a last step can you add it to the docs? These are the files you need to change:
```
docs/source/api/algorithm_functions/shortest_paths.rst
docs/source/api/pygraph_api_functions.rst
docs/source/api/pydigraph_api_functions.rst
```

You will also need to write a short docstring adding a description of the function you implemented. I can do it for you if you want

2024-01-06 16:49 UTC, kazuki0824 commented
@IvanIsCoding Can you please tell me the file location where to add the docstring?

2024-01-06 18:46 UTC, IvanIsCoding commented
> @IvanIsCoding Can you please tell me the file location where to add a docstring?

You add a comment in the Rust code. See the Floyd Warshall one for example: https://github.com/Qiskit/rustworkx/blob/99f975662a72dbd879c086d37ea32d429f5ef07d/src/shortest_path/mod.rs#L868

2024-01-07 07:39 UTC, kazuki0824 commented
@IvanIsCoding Thanks for your advice. It's done.

2024-01-07 14:48 UTC, IvanIsCoding approved these changes
LGTM, I will add the release notes and merge it today. Thanks for your contribution!

2024-01-07 17:46 UTC, IvanIsCoding commented
I don't have permission to edit your branch so I will merge this and add the release notes in a new PR

2024-01-07 17:46 UTC, merged