Add edge betweenness centrality
Qiskit/rustworkx pull request #799
Opened 2023-02-01 11:48 UTC by tapanih

Related to #441

Added edge betweenness centrality to rustworkx and rustworkx-core. It is mostly based on betweenness centrality with some modifications.

2023-02-06 21:33 UTC, jlapeyre commented
Thanks for the contribution!
I think it would be a good idea to cross-reference (vertex) betweeness centrality somehow. networkx has quite a bit more of this. But I don't want to overload this PR. Also, rustworkx is less complete and has less need at present. networkx implements something like [forty-two centralities](https://networkx.org/documentation/stable/reference/algorithms/centrality.html). With this PR, rustworkx will have three.

But I think including something like a "See also" like [this](https://github.com/networkx/networkx/blob/226de67121e8f7d0b44cdce6f053a43f70c034d6/networkx/algorithms/centrality/betweenness.py#L68-L71) would be useful.

2023-02-07 03:25 UTC, jlapeyre commented on releasenotes/notes/add-edge-betweenness-centrality-8de06bf716caece0.yaml
> +    centrality of all edges in a given graph.
* There are several lines above that consist only of whitespace. This should be removed (only a single newline for each such line.)
* There should be a newline at the end of the file.

2023-02-07 03:47 UTC, jlapeyre requested changes

2023-02-07 03:47 UTC, jlapeyre commented on releasenotes/notes/add-edge-betweenness-centrality-8de06bf716caece0.yaml
> +    centrality of all edges in a given graph.
File needs a newline.

2023-02-07 03:47 UTC, jlapeyre commented on src/centrality.rs
> +/// Compute the edge betweenness centrality of all edges in a :class:`~PyGraph`.
The edge and vertex centrality functions should be next to each other in this file, as they are more closely related to each other than to the eigenvector centrality... unless there is another good reason for the current order.

2023-02-09 04:54 UTC, jlapeyre approved these changes
Looks good.

2023-03-09 13:03 UTC, mtreinish approved these changes
This LGTM, thanks for pushing this! (and sorrt for the delay in final review)

2023-03-09 13:32 UTC, merged